spring.application.name=esex

# Configurazione Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB


# Limite dimensione foto caricate
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Configurazione MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/esex
spring.datasource.username=root
spring.datasource.password=4nt4n1
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Chiave personalizzata per l'autenticazione del Frontend Angular
app.security.api-key=Matrimonio-Segreto-2026-XYZ123
